version: '3.8'

services:
  php:
     image: phpmyadmin/phpmyadmin
     links:
       - mysql:db
     depends_on:
       - mysql

  mysql:
    image: k0st/alpine-mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=datedebate
      - MYSQL_USER=root
      - MYSQL_PASSWORD=!krems 

  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ./src:/usr/share/nginx/html
    links:
    - php
